version: '3'
services:
        web:
                image: flask_port_v1
                environment:
                        - CRYPTO_KEY=${CRYPTO_KEY}
                build: .
                ports:
                        - "8181:8181"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
